@dev @local
Feature: 39 Messaging Bulk Processing

# This feature file is designed to load a high amount of payment messages into pay-enrichment
# for the purpose of performance testing of the service and its ability to process messages in bulk

  Scenario: 01 Load 5000 payment messages into pay-enrichment

  #Due to call stack limits, 5000 has been determined as the best amount of messages to send in one batch. 
  #This scenario can be re-run multiple times to increase the total number of messages sent however instructions
  #found in Step Definition - 'When I send 5000 payment messages using template "paymentFileMessage" to the service bus topic "ffc-pay-request-aw"'
  #must be followed and the correct code must be commented/uncommented to avoid data duplication

    Given I restart the local environment
    Given I start the messaging service for the service bus topic "ffc-pay-request-dev"
    When I send 5000 payment messages using template "paymentFileMessage" to the service bus topic "ffc-pay-request-dev"

  Scenario: 02 Load 5000 return messages

  #This scenario repeats the previous process but sends return messages for payment requests generated by Scenario 1

    Given I start the messaging service for the service bus topic "ffc-pay-return-dev"
    When I send 5000 return messages using template "returnFileMessage" to the service bus topic "ffc-pay-return-dev"
