@dev
Feature: 39 Messaging Bulk Processing
# npm run cypress:dev:one -- "cypress\e2e\features\39_MessagingBulkProcessing.feature"
# npm run cypress:local:one -- "cypress\e2e\features\39_MessagingBulkProcessing.feature"

# This feature file is designed to load a high amount of payment messages into pay-enrichment
# for the purpose of performance testing of the service and its ability to process messages in bulk

# ╔══════════════════════════════════════════════════════════════════════╗
# ║                  FFC PAY BULK MESSAGING PROCESSING                   ║
# ╚══════════════════════════════════════════════════════════════════════╝

#          PAYMENTS                RETURNS                   PPAs
#     ┌────────────────┐     ┌────────────────┐     ┌────────────────┐
#     │ ffc-pay-request│────>│ ffc-pay-return │────>│ ffc-pay-request│
#     └────────────────┘     └────────────────┘     └────────────────┘
#               │                       │                      │
#               ▼                       ▼                      ▼

#       paymentRequests      completedPaymentRequests     paymentRequests
#         request=1                                        request=2

#               │                       │                      │
#               ▼                       ▼                      ▼

#         WAIT FOR DB           WAIT FOR DB           WAIT FOR DB
#             POLL                 POLL                   POLL

#               │                       │                      │
#               └───────────────┬───────┴──────────────────────┘
#                               │
#                               ▼

#                    SHOULD ARRIVE IN AWAITING DEBT DATA
                          

#     IF IT ARRIVES IN AWAITING MANUAL LEDGER, SOMETHING IS UP WITH PPAS PROCESSING BEFORE RETURN/PAYMENTS
                         
# ════════════════════════════════════════════════════════════════════════

# RUN ORDER OF BELOW

# 1. SEND PAYMENTS
# 2. WAIT FOR PAYMENTS
# 3. SEND RETURNS
# 4. WAIT FOR RETURNS
# 5. SEND PPAs
# 6. WAIT FOR PPAs
#     7. CHECK REQUEST EDITOR --LET PPAS PROCESS FOR A BIT

# ════════════════════════════════════════════════════════════════════════

# USEFUL INFO BEFORE RUNNING :

# NEVER REUSE A BATCH RANGE AS THIS WILL GIVE YOU ISSUES
# MAX 5 CHARS
# MAKE SURE AMOUNT MATCHES OF MESSAGES/RETURNS/PPA BEFORE RUNNING

# ════════════════════════════════════════════════════════════════════════

#     EXPECTED RESULT

# Payments Received 
# Payments Processed 
# Returns Matched 
# PPAs Created 
# ROUTED TO Awaiting Debt Data IN REQUEST EDITOR 

# ════════════════════════════════════════════════════════════════════════

# TODO 

# -PPA polling is not reliable - they will only go one once the returns processed but they need to wait until the ledger split happens to be confirmed succesful - need to poll a DB somewhere to make sure this has happened before we can pass the test
# ════════════════════════════════════════════════════════════════════════


  Scenario: 01 Load X amount of payment messages into pay-enrichment

  #Due to call stack limits, 5000 has been determined as the best amount of messages to send in one batch. 
  #This scenario can be re-run multiple times to increase the total number of messages sent however instructions
  #found in Step Definition - 'When I send 5000 payment messages using template "paymentFileMessage" to the service bus topic "ffc-pay-request-auto"'
  #must be followed and the correct code must be commented/uncommented to avoid data duplication

    Given I restart the local environment
    Given I start the messaging service for the service bus topic "ffc-pay-request-dev"
    When I send 300 payment messages using template "paymentFileMessage" to the service bus topic "ffc-pay-request-dev" with the batch number 91000
    Then I wait for 300 payment requests to be ready for settlement for batch 91000
 
  # Scenario: 02 Load X amount of return messages

  # #This scenario repeats the previous process but sends return messages for payment requests generated by Scenario 1

  #   Given I start the messaging service for the service bus topic "ffc-pay-return-dev"
  #   When I send 300 return messages using template "returnFileMessage" to the service bus topic "ffc-pay-return-dev" with the batch number 91000
  #   Then I wait for 300 returns to be processed for batch 91000

  Scenario: 03 Load X amount of PPA messages
    Given I start the messaging service for the service bus topic "ffc-pay-request-dev"
    When I send 300 ppa messages using template "ppaFileMessage" to the service bus topic "ffc-pay-request-dev" with the batch number 91000
    Then I wait for 300 ppas to be processed for batch 91000