require('dotenv').config();
const { BlobServiceClient } = require('@azure/storage-blob');
const fs = require('fs');
const path = require('path');
const csv = require('csv-parser');

async function downloadPaymentsBlobById (containerName, downloadDir, scheme) {

  //This function downloads report from Azure Blob storage and checks that relevant values are correct
  var blobServiceClient = null;

  if (scheme === 'dps') {
    blobServiceClient = BlobServiceClient.fromConnectionString(process.env.DPSBLOBCONNECTIONSTRING);
  } else {
    blobServiceClient = BlobServiceClient.fromConnectionString(process.env.PAYMENTSBLOBCONNECTIONSTRING);
  }
  console.log('Blob Service Client = ' + blobServiceClient.url);
  console.log('Container name = ' + containerName);
  const containerClient = blobServiceClient.getContainerClient(containerName);
  console.log('Container client = ' + containerClient.url);

  let blobs = containerClient.listBlobsFlat();
  let matchingBlob = null;

  var partialFileName = '';
  switch (scheme) {
  case 'glos': partialFileName = 'outbound/FFCFC_0001'; break;
  case 'imps': partialFileName = 'outbound/FFCIMPS_0001'; break;
  case 'genesis': partialFileName = 'outbound/FFCES_0001'; break;
  case 'dps': partialFileName = 'outbound/FFCBGAN2023'; break;
  case 'vet visits': partialFileName = 'outbound/FFCVV_0001'; break;
  case 'cohtr': partialFileName = 'outbound/FFCSITICOHTR_0001'; break;
  case 'cohtc': partialFileName = 'outbound/FFCSITICOHTC_0001'; break;
  case 'cs': partialFileName = 'outbound/FFCCS_0001'; break;
  case 'bps': partialFileName = 'outbound/FFCBPS_0001'; break;
  case 'lump sums': partialFileName = 'outbound/FFCLS_0001'; break;
  case 'sfi expanded': partialFileName = 'outbound/FFCESFIO_0001'; break;
  case 'delinked': partialFileName = 'outbound/FFCDP_0001'; break;
  case 'sfi pilot': partialFileName = 'outbound/FFCSFIP_0001'; break;
  case 'sfi23': partialFileName = 'outbound/FFCSFIA_0001'; break;
  default: throw new Error(`Unknown scheme: ${scheme}`);
  }

  //This finds the file by it's partial name as they are autogenerated with names predicated on time of creation
  for await (const blob of blobs) {
    if (blob.name.includes(partialFileName)) {
      matchingBlob = blob;
      break;
    }
  }

  if (!matchingBlob) {
    console.error(`⚠️ No blobs found matching the partial name: "${partialFileName}"`);
    return;
  }

  console.log(`Matched Blob: ${matchingBlob.name}`);

  const downloadPath = path.join(downloadDir, path.basename(matchingBlob.name));
  console.log('Download path = ' + downloadPath);

  //Downloads file to cypress/downloads

  try {
    await containerClient.getBlobClient(matchingBlob.name).downloadToFile(downloadPath);
    console.log(`📍 Saved to: ${downloadPath}`);

  } catch (error) {
    console.log(error);
    throw error;
  }

  const results = [];
  var requiredValues = [];
  switch (scheme) {
  case 'glos': requiredValues = [
    '2015', 'SOS710', 'DRD05', 'FC00'
  ]; break;
  case 'imps': requiredValues = [
    '2022', '25057', 'DOM00', 'RP00', 'J07494'
  ]; break;
  case 'genesis' : requiredValues = [
    '2022', 'SOS229', 'EXQ00', 'NE00'
  ]; break;
  case 'dps' : requiredValues = [
    '2410', '766951', '1PC09913', '14618.00', 'GBP'
  ]; break;
  case 'vet visits' : requiredValues = [
    '2025', 'SOS210', 'DOM10', '1201.00', 'RP00'
  ]; break;
  case 'cohtr' : requiredValues = [
    '2025', 'SOS710', 'DRD10', '100000.00', 'RP00'
  ]; break;
  case 'cohtc' : requiredValues = [
    '2025', 'SOS710', 'DRD10', '100000.00', 'RP00'
  ]; break;
  case 'cs' : requiredValues = [
    '2025', 'SOS710', 'DRD10', '100000.00', 'RP00'
  ]; break;
  case 'bps' : requiredValues = [
    '2025', '80101', 'DOM10', '100000.00', 'RP00'
  ]; break;
  case 'lump sums' : requiredValues = [
    '2025', '80101', 'DRD10', '100000.00', 'RP00'
  ]; break;
  case 'sfi expanded' : requiredValues = [
    '2025', '80101', 'DRD10', '100000.00', 'RP00'
  ]; break;
  case 'delinked' : requiredValues = [
    '2025', '80101', 'DRD10', '100000.00', 'RP00'
  ]; break;
  case 'sfi pilot' : requiredValues = [
    '2025', '80101', 'DRD10', '100000.00', 'RP00'
  ]; break;
  case 'sfi23' : requiredValues = [
    '2023', '80101', 'DRD10', '100000.00', 'RP00'
  ]; break;
  default: throw new Error(`Unknown scheme: ${scheme}`);
  }

  await new Promise((resolve, reject) => {
    fs.createReadStream(downloadPath)
      .pipe(csv())
      .on('data', (data) => results.push(data))
      .on('end', () => {
        console.log('Extracted CSV Data:\n', results);

        // Flatten all values from all rows into a single array of strings
        const allValues = results.flatMap(row => Object.values(row).map(String));

        // Check if every required value is present
        const missingValues = requiredValues.filter(val => !allValues.includes(val));

        if (missingValues.length === 0) {
          console.log('✅ All required values are present in the CSV.');
        } else {
          console.error(`❌ Missing values: ${missingValues.join(', ')}`);
          throw new Error('CSV does not contain all expected data.');
        }

        resolve();
      })
      .on('error', (err) => {
        console.error(`⚠️ Error reading CSV file: ${err.message}`);
        reject(err);
        throw err;
      });
  });

  return downloadPath;


}

module.exports = downloadPaymentsBlobById;